file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/fmin/getDistParamError.p DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Debug)
file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/fmin/getDistParamError.p DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Release)

file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/fmin/GetFMin.p DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Debug)
file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/fmin/GetFMin.p DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Release)
